apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: client-onboarding-dev

namespace: app

resources:
- ../../base
- external-secret-patch.yaml

patches:
- path: ingress-patch.yaml

configMapGenerator:
- name: client-onboarding-config
  literals:
  - PYTHONPATH=server
  - CLIENT_SECRET=Tl8ecR4pUh-CYqt7KRWqiCxURCpHb$#NxK_XWQLe
  - REQUEST_TIMEOUT=300
  - ENABLE_DOCS=True
  - AWS_REGION=eu-central-1
  - INQUIRIES_TIMEOUT=60000
  - SSL_CERT_CHAIN_SECRET_NAME=dev-eks-internal-services-ssl-ca-crt
  - CLIENT_ID=o28x29ywvGBnf22WLf8NDlKZg5oQDc
  - FERNET_KEY=daYUf0bLc_e14x1aoprgcEpLp2RfSA-01FACKa6bZ2Q=

images:
- name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/client-onboarding
  newTag: version_3.7.5_e43e2df_375

commonLabels:
  environment: dev
  version: "3.7.5"
