apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ngliveness-qa375

namespace: app

resources:
  - ../../base
  - external-secret-patch.yaml

configMapGenerator:
  - name: ngliveness-config
    literals:
      - AUDIT=true
      - DISABLE_LOG_TO_FILE=true
      - SETUP_RABBITMQ=true
      - AWS_DEFAULT_REGION=eu-central-1
      - SESSIONS_SCHEDULER_INTERVAL_SECONDS=20
      - DEFAULT_COMPANY=63e353cbc81e405c6c692ffa
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/gcp_credentials.json
      - EXTRA_REDIS_TTL_SECONDS=300
      - TIMED_OUT_SESSIONS_COMPLETION_DELAY_SECONDS=10
      - AUTH_DB_SCHEMA=test_authorization_375
      - IDRND_URI=https://idrnd.qa-eks.internal-services:8443
      - SSL_CERT_CHAIN_SECRET_NAME=qa-internal-services-ssl-ca-crt
      - DB_SCHEMA=test_authorization_375
      - KINESIS_STREAM_NAME=test_purple_events
      - IDENTITY_POOL_ID=eu-central-1:6d48067d-753f-4c32-ae14-14b9a153985b

commonLabels:
  environment: qa
