apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idrnd-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
    external-dns.alpha.kubernetes.io/hostname: idrnd.dev-eks.internal-services
spec:
  rules:
  - host: idrnd.dev-eks.internal-services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: idrnd-service
            port:
              number: 8443
