apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: idrnd-dev

namespace: app

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: idrnd-ingress

configMapGenerator:
- name: idrnd-config
  literals:
  - SERVER_SSL_ENABLED=true

images:
- name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/idrnd
  newTag: idface-server-prod-1.49.2

commonLabels:
  environment: dev
  version: "1.49.2"

commonAnnotations:
  environment: "development"
