apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngocr
  namespace: app
  labels:
    app: ngocr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngocr
  template:
    metadata:
      labels:
        app: ngocr
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: ngocr
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/ng_ocr:latest
        ports:
        - name: 5010-tcp
          containerPort: 5010
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "2Gi"
          limits:
            cpu: "3584m"
            memory: "7Gi"
        envFrom:
        - configMapRef:
            name: ngocr-config
        - secretRef:
            name: ngocr-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
