apiVersion: v1
kind: Service
metadata:
  name: ngocr-service
  namespace: app
  labels:
    app: ngocr
spec:
  ports:
  - port: 5010
    targetPort: 5010
    protocol: TCP
    name: 5010-tcp
  selector:
    app: ngocr
