apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ngfacematch-qa375

namespace: app

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base
  - external-secret-patch.yaml

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: ngfacematch-ingress

configMapGenerator:
  - name: ngfacematch-config
    literals:
      - SUPPORT_1_TO_MANY=true
      - AWS_DEFAULT_REGION=eu-central-1
      - ENABLE_ANALYTICS=true
      - ENABLE_HTTPS=true
      - SUPPORT_AGE_AND_GENDER=true
      - KINESIS_STREAM_NAME=test_purple_events

images:
  - name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/ngfacematch
    newTag: version_3.7.5_51c0e70_49

commonLabels:
  environment: qa
  version: "3.7.5"

commonAnnotations:
  environment: "qa"
