apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies
  namespace: platform
  labels:
    app: companies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: companies
  template:
    metadata:
      labels:
        app: companies
    spec:
      serviceAccountName: platform-services-sa
      containers:
      - name: nginx
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/platform_nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-80
          containerPort: 80
          protocol: TCP
        - name: http-8040
          containerPort: 8040
          protocol: TCP
        - name: http-8050
          containerPort: 8050
          protocol: TCP
        - name: http-8060
          containerPort: 8060
          protocol: TCP
        - name: http-8080
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: companies-config
        - secretRef:
            name: companies-secrets
        resources:
          requests:
            cpu: "512m"
            memory: "1Gi"
          limits:
            cpu: "1024m"
            memory: "2Gi"

      - name: core
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/core:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: core-5002
          containerPort: 5002
          protocol: TCP
        envFrom:
        - configMapRef:
            name: companies-config
        - secretRef:
            name: companies-secrets
        resources:
          requests:
            cpu: "512m"
            memory: "1Gi"
          limits:
            cpu: "1024m"
            memory: "2Gi"

      - name: gateway
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: gateway-5008
          containerPort: 5008
          protocol: TCP
        envFrom:
        - configMapRef:
            name: companies-config
        - secretRef:
            name: companies-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
        resources:
          requests:
            cpu: "512m"
            memory: "1Gi"
          limits:
            cpu: "1024m"
            memory: "2Gi"
