apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: console-qa375

namespace: app

resources:
  - ../../base
  - external-secret-patch.yaml

patches:
  - path: ingress-patch.yaml

configMapGenerator:
  - name: console-config
    literals:
      - CAPTCHA_SOLVED_DELAY=250
      - PYTHONPATH=server
      - REQUEST_TIMEOUT=300
      - AWS_REGION=eu-central-1
      - ENABLE_DOCS=True
      - CAPTCHA_AFTER_FAILED_LOGINS=3
      - CAPTCHA_DOMAINS=purpleray.com
      - SSL_CERT_CHAIN_SECRET_NAME=qa-internal-services-ssl-ca-crt
      - CAPTCHA_ENABLED=1

images:
  - name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/console
    newTag: version_3.7.5_008e4cf_488

commonLabels:
  environment: qa
  version: "3.7.5"
