apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: app
  labels:
    app: authorization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: authorization
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/authorization:latest
        ports:
        - name: 5800-tcp
          containerPort: 5800
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "1Gi"
          limits:
            cpu: "2048m"
            memory: "2Gi"
        envFrom:
        - configMapRef:
            name: authorization-config
        - secretRef:
            name: authorization-secrets
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
