apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authorization-ingress
  namespace: app
  labels:
    app: authorization
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 5800}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/ttl: "300"
    alb.ingress.kubernetes.io/healthcheck-path: /alive
    alb.ingress.kubernetes.io/healthcheck-port: '5800'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
spec:
  ingressClassName: alb
  rules:
  - host: authorization.internal-services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authorization-service
            port:
              number: 5800
