apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ngocr-qa375

namespace: app

resources:
  - ../../base
  - external-secret-patch.yaml

configMapGenerator:
  - name: ngocr-config
    literals:
      - EXTRA_REDIS_TTL_SECONDS=300
      - SETUP_RABBITMQ=false
      - AWS_DEFAULT_REGION=eu-central-1
      - TIMED_OUT_SESSIONS_COMPLETION_DELAY_SECONDS=10
      - SESSIONS_SCHEDULER_INTERVAL_SECONDS=20
      - OMP_NUM_THREADS=1
      - SSL_CERT_CHAIN_SECRET_NAME=qa-internal-services-ssl-ca-crt
      - AUTH_DB_SCHEMA=test_authorization_375
      - REGULA_URL=https://api.regulaforensics.com/api/process
      - DB_SCHEMA=test_authorization_375
      - KINESIS_STREAM_NAME=test_purple_events
      - IDENTITY_POOL_ID=eu-central-1:6d48067d-753f-4c32-ae14-14b9a153985b

commonLabels:
  environment: qa
