apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness
  namespace: app
  labels:
    app: liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness
  template:
    metadata:
      labels:
        app: liveness
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: liveness
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/liveness:latest
        ports:
        - name: 5050-tcp
          containerPort: 5050
          protocol: TCP
        resources:
          requests:
            cpu: "2048m"
            memory: "5Gi"
          limits:
            cpu: "4096m"
            memory: "7Gi"
        envFrom:
        - configMapRef:
            name: liveness-config
        - secretRef:
            name: liveness-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
