apiVersion: v1
kind: Service
metadata:
  name: liveness-service
  namespace: app
  labels:
    app: liveness
spec:
  type: ClusterIP
  ports:
  - name: 5050-tcp
    port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: liveness
