# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: company1-gateway-external
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/your-certificate-id
#     alb.ingress.kubernetes.io/group.name: dev-external
#     alb.ingress.kubernetes.io/load-balancer-name: dev-eks-external-alb
#     external-dns.alpha.kubernetes.io/hostname: dev-company1-gateway.purpleray.com
# spec:
#   ingressClassName: alb
#   rules:
#     - host: dev-company1-gateway.purpleray.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: company1-gateway-service
#                 port:
#                   number: 8040
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: company1-gateway-internal
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internal
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":8040}]'
#     alb.ingress.kubernetes.io/group.name: dev-internal
#     alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
#     external-dns.alpha.kubernetes.io/hostname: company1.dev.internal-services
# spec:
#   ingressClassName: alb
#   rules:
#     - host: company1.dev.internal-services
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: company1-gateway-service
#                 port:
#                   number: 8040
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: company1-core-internal
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internal
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":5002}]'
#     alb.ingress.kubernetes.io/group.name: dev-internal
#     alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
#     external-dns.alpha.kubernetes.io/hostname: company1.dev.internal-services
# spec:
#   ingressClassName: alb
#   rules:
#     - host: company1.dev.internal-services
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: company1-core-service
#                 port:
#                   number: 5002
