namespaces:
  - name: app
    labels:
      component: application-services
    annotations:
      description: "Namespace for all application services"
  - name: platform
    labels:
      component: platform-services
    annotations:
      description: "Namespace for all platform services (Companies)"

sharedConfig:
  enabled: true
  name: shared-configmap
  namespace: app
  labels: {}
  annotations: {}
  data: {}

traefikAlb:
  enabled: false
  namespace: traefik-system
  ingressClassName: alb
  host: ""
  service:
    name: traefik
    port: 80
  annotations:
    alb.ingress.kubernetes.io/group.name: ""
    alb.ingress.kubernetes.io/load-balancer-name: ""
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
