apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngfacematch
  namespace: app
  labels:
    app: ngfacematch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngfacematch
  template:
    metadata:
      labels:
        app: ngfacematch
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: ngfacematch
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/ngfacematch:latest
        ports:
        - name: 3000-tcp
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "3Gi"
          limits:
            cpu: "2048m"
            memory: "6Gi"
        envFrom:
        - configMapRef:
            name: ngfacematch-config
        - secretRef:
            name: ngfacematch-secrets
