apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngfacematch-ingress
  namespace: app
  labels:
    app: ngfacematch
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 3000}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /alive
    alb.ingress.kubernetes.io/healthcheck-port: '3000'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
spec:
  ingressClassName: alb
  rules:
  - host: ngfacematch.internal-services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ngfacematch-service
            port:
              number: 3000
