apiVersion: v1
kind: Service
metadata:
  name: ngfacematch-service
  namespace: app
  labels:
    app: ngfacematch
spec:
  type: ClusterIP
  ports:
  - name: ngfacematch-3000-tcp
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: ngfacematch
