apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-presentation-detection
  namespace: app
  labels:
    app: liveness-presentation-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: liveness-presentation-detection
  template:
    metadata:
      labels:
        app: liveness-presentation-detection
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: liveness-presentation-detection
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/liveness_presentation_detection:idface-server-prod-1.49.2
        ports:
        - name: pre-8443-tcp
          containerPort: 8443
          protocol: TCP
        resources:
          requests:
            cpu: "2048m"
            memory: "5Gi"
          limits:
            cpu: "4096m"
            memory: "7Gi"
        envFrom:
        - configMapRef:
            name: liveness-presentation-detection-config
        - secretRef:
            name: liveness-presentation-detection-secrets
