apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: liveness-presentation-detection-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - scaledobject-keda.yaml

commonLabels:
  app: liveness-presentation-detection
  managed-by: kustomize
