apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shared-infrastructure
  annotations:
    description: "Shared infrastructure for qa environment"

resources:
- ../../base
- serviceaccount.yaml
- authorization-configmap.yaml
- authorization-configmap-platform.yaml

commonLabels:
  environment: qa

commonAnnotations:
  environment: qa
