apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-statement
  namespace: app
  labels:
    app: video-statement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-statement
  template:
    metadata:
      labels:
        app: video-statement
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: video-statement
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/video_statement:latest
        ports:
        - name: 5020-tcp
          containerPort: 5020
          protocol: TCP
        resources:
          requests:
            cpu: "512m"
            memory: "1Gi"
          limits:
            cpu: "1024m"
            memory: "2Gi"
        envFrom:
        - configMapRef:
            name: video-statement-config
        - secretRef:
            name: video-statement-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
