apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-statement-ingress
  namespace: app
  labels:
    app: video-statement
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing

spec:
  ingressClassName: alb
  rules:
  - host: video-statement-eks.purpleray.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: video-statement-service
            port:
              number: 5020
