apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: video-statement-base

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- secret.yaml

commonLabels:
  app: video-statement
  managed-by: kustomize
