apiVersion: v1
kind: Service
metadata:
  name: video-statement-service
  namespace: app
  labels:
    app: video-statement
spec:
  type: ClusterIP
  ports:
  - name: stt-5020-tcp
    port: 5020
    targetPort: 5020
    protocol: TCP
  selector:
    app: video-statement
