apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies
spec:
  template:
    spec:
      containers:
      - name: nginx
        envFrom:
        - configMapRef:
            name: company2-common-config
        - secretRef:
            name: company2-companies-secrets
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      - name: core
        envFrom:
        - configMapRef:
            name: company2-common-config
        - secretRef:
            name: company2-companies-secrets
        - configMapRef:
            name: company2-core-config
      - name: gateway
        envFrom:
        - configMapRef:
            name: company2-common-config
        - secretRef:
            name: company2-companies-secrets
        - configMapRef:
            name: company2-gateway-config
      volumes:
      - name: nginx-config
        configMap:
          name: company2-nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf