apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-external-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-external
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/5152bcf9-4464-4bb3-8953-014a10d654c5
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-external-alb
    external-dns.alpha.kubernetes.io/hostname: dev-eks-company2-gateway.purpleray.com
spec:
  rules:
    - host: dev-eks-company2-gateway.purpleray.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: company2-nginx-service
                port:
                  number: 8040
