apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-internal-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
    external-dns.alpha.kubernetes.io/hostname: company2.dev-eks.internal-services
spec:
  rules:
    - host: company2.dev-eks.internal-services
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: company2-nginx-service
                port:
                  number: 8040
