apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: idrnd-documents-liveness-qa375

namespace: app

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: idrnd-documents-liveness-ingress

configMapGenerator:
  - name: idrnd-documents-liveness-config
    literals:
      - SERVER_ALLOW_CORS=true
      - IDLIVEDOC_SERVER_AVAILABLE_PIPELINES=default-sr,default-pc,default-ps,default-dm
      - SERVER_SSL_ENABLED=true

images:
  - name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/idrnd_document_liveness
    newTag: idlivedoc-server-prod-sr-pc-ps-dm_3.3.2

commonLabels:
  environment: qa
  version: "3.3.2"

commonAnnotations:
  environment: "qa"
