image:
  tag: version_3.7.5_16f8647_254

service:
  labels:
    version: "3.7.5"

config:
  data:
    CONSOLE_CLIENT_ID: "172Tvy5Yrb3h4XMY3daz7Xr1vzY1gh"
    AUTH_DB_SCHEMA: "test_authorization_375"
    AWS_DEFAULT_REGION: "eu-central-1"
    ONBOARDING_CLIENT_ID: "o28x29ywvGBnf22WLf8NDlKZg5oQDc"
    AUDIT_EVENTS_STREAM_NAME: "test_audit_events"
    ENABLE_DOCS: "true"
    PORTAL_CLIENT_ID: "0nqFGaPkYUhSbTU2Nm0Rylp0sbWaIM"
    ENABLE_HTTPS: "true"
    SSL_CERT_CHAIN_SECRET_NAME: "qa-internal-services-ssl-ca-crt"
    ANALYTICS_EVENTS_STREAM_NAME: "test_purple_events"
    CHALLENGE_TOKEN_KEY: "dd5ad3d8-8a35-4e86-92ce-4dfc72d05590"
    AUDIT_EVENTS_IS_FIRE_EVENT: "true"
    ANALYTICS_EVENTS_IS_FIRE_EVENT: "true"
    DB_SCHEMA: "test_authorization_375"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: qa-internal
    alb.ingress.kubernetes.io/load-balancer-name: qa-eks-internal-alb
    

externalSecrets:
  - name: authorization-external-secret
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: authorization-secrets
    data:
      - secretKey: SSL_KEY
        remoteRef:
          key: qa-internal-services-ssl-key
      - secretKey: SSL_CERT
        remoteRef:
          key: qa-internal-services-ssl-cert
      - secretKey: SSL_KEY_PASSWORD
        remoteRef:
          key: qa-internal-services-ssl-key-password
  - name: authorization-ssm-external-secret
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: authorization-secrets
    data:
      - secretKey: DB_URI
        remoteRef:
          key: DB_URI-authorization-qa
      - secretKey: MAINTENANCE_KEY
        remoteRef:
          key: MAINTENANCE_KEY-qa-v35
  
