replicaCount: 2
service:
  name: authorization
  port: 5800
  targetPort: 5800
  ports:
  - name: 5800-tcp
    port: 5800
    targetPort: 5800
    protocol: TCP
  

ingress:
  internal: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 5800}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/ttl: "300"
    alb.ingress.kubernetes.io/healthcheck-path: /alive
    alb.ingress.kubernetes.io/healthcheck-port: '5800'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    
  paths:
    - path: /
      pathType: Prefix
      serviceName: authorization-service
      port: 5800
    

image:
  repository: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/authorization
  tag: latest

resources:
  requests:
    cpu: "1024m"
    memory: "1Gi"
  limits:
    cpu: "2048m"
    memory: "2Gi"
  

config:
  create: true
  name: authorization-config
  data: {}

secret:
  create: false
  name: authorization-secrets

externalSecrets: []

extraEnv:
  - name: DOMAIN
    valueFrom:
      configMapKeyRef:
        name: shared-configmap
        key: AUTH_URL
  

scaledObject:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 3
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
    - type: memory
      metadata:
        type: Utilization
        value: "80"
