
replicaCount: 2

image:
  tag: main_a3e4242_8

service:
  labels:
    version: ""

config:
  data:
    COMPANY_NAME: "company2"
    ENV: "dev"

ingress:
  annotations:
    {}
    

externalSecrets:
  - name: companies-external-secret
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: company2-companies-secrets
    data:
      - secretKey: SSL_KEY
        remoteRef:
          key: dev-eks-internal-services-ssl-key
      - secretKey: SSL_CERT
        remoteRef:
          key: dev-eks-internal-services-ssl-cert
      - secretKey: SSL_KEY_PASSWORD
        remoteRef:
          key: dev-eks-internal-services-ssl-key-password
      - secretKey: DATABASE_PASSWORD
        remoteRef:
          key: rds_credentials_dev
          property: password
      - secretKey: DATABASE_USER
        remoteRef:
          key: rds_credentials_dev
          property: username
      - secretKey: SPRING_DATASOURCE_PASSWORD
        remoteRef:
          key: rds_credentials_dev
          property: password
      - secretKey: SPRING_DATASOURCE_USERNAME
        remoteRef:
          key: rds_credentials_dev
          property: username
      - secretKey: S3_ACCESS_KEY
        remoteRef:
          key: S3_KEYS
          property: ACCESS_KEY
      - secretKey: S3_SECRET_KEY
        remoteRef:
          key: S3_KEYS
          property: SECRET_KEY
      - secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          key: S3_KEYS
          property: ACCESS_KEY
      - secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          key: S3_KEYS
          property: SECRET_KEY
      - secretKey: GATEWAY_CLIENT_ID
        remoteRef:
          key: dev_auth_gateway_service_client
          property: GATEWAY_CLIENT_ID
      - secretKey: GATEWAY_CLIENT_SECRET
        remoteRef:
          key: dev_auth_gateway_service_client
          property: GATEWAY_CLIENT_SECRET
      - secretKey: GATEWAY_CONFIG_CLIENT_ID
        remoteRef:
          key: dev_auth_gateway_config
          property: GATEWAY_CONFIG_CLIENT_ID
      - secretKey: GATEWAY_CONFIG_CLIENT_SECRET
        remoteRef:
          key: dev_auth_gateway_config
          property: GATEWAY_CONFIG_CLIENT_SECRET
      - secretKey: CLIENT_API_CONFIG_CLIENT_ID
        remoteRef:
          key: dev_auth_gateway_config
          property: GATEWAY_CONFIG_CLIENT_ID
      - secretKey: CLIENT_API_CONFIG_CLIENT_SECRET
        remoteRef:
          key: dev_auth_gateway_config
          property: GATEWAY_CONFIG_CLIENT_SECRET
      - secretKey: DATABASE_URL
        remoteRef:
          key: rds_credentials_dev
          property: DEV_SPRING_PROXY_URL
      - secretKey: SQL_DB_URI
        remoteRef:
          key: rds_credentials_dev
          property: DEV_EKSCOMPANY2_PROXY_URL
  - name: companies-ssm-external-secret
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: company2-companies-secrets
    data:
      - secretKey: DB_URI
        remoteRef:
          key: DB_URI-auth-eks-dev
      - secretKey: MAINTENANCE_KEY
        remoteRef:
          key: MAINTENANCE_KEY-dev
      - secretKey: SPRING_DATASOURCE_URL
        remoteRef:
          key: SPRING_DATASOURCE_URL-dev
      - secretKey: SPRING_DATASOURCE_URL2
        remoteRef:
          key: SPRING_DATASOURCE_URL2-dev
      - secretKey: REDIS_URI
        remoteRef:
          key: REDIS_URI-dev
  
