replicaCount: 2
service:
  name: facesplit
  port: 3030
  targetPort: 3030
  ports:
  - name: 3030-tcp
    port: 3030
    targetPort: 3030
    protocol: TCP
  

ingress:
  internal: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
    
  paths:
    - path: /
      pathType: Prefix
      serviceName: facesplit-service
      port: 3030
    

image:
  repository: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/pia_face
  tag: latest

resources:
  requests:
    cpu: "1024m"
    memory: "1Gi"
  limits:
    cpu: "2048m"
    memory: "2Gi"
  

config:
  create: true
  name: facesplit-config
  data: {}

secret:
  create: false
  name: facesplit-secrets

externalSecrets: []

scaledObject:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 3
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
    - type: memory
      metadata:
        type: Utilization
        value: "70"
