image:
  tag: idlivedoc-server-prod-sr-pc-ps-dm_3.3.2

service:
  labels:
    version: "3.3.1"

config:
  data:
    SERVER_ALLOW_CORS: "true"
    IDLIVEDOC_SERVER_AVAILABLE_PIPELINES: "default-sr,default-pc,default-ps,default-dm"
    SERVER_SSL_ENABLED: "true"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
    external-dns.alpha.kubernetes.io/ttl: "300"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/5152bcf9-4464-4bb3-8953-014a10d654c5
    
