replicaCount: 1
service:
  name: idrnd-documents-liveness
  port: 8443
  targetPort: 8443
  ports:
  - name: 8443-tcp
    port: 8443
    targetPort: 8443
    protocol: TCP
  

ingress:
  internal: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api_version
    alb.ingress.kubernetes.io/healthcheck-port: '8443'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    
  paths:
    - path: /
      pathType: Prefix
      serviceName: idrnd-documents-liveness-service
      port: 8443
    

image:
  repository: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/idrnd_document_liveness
  tag: latest

resources:
  requests:
    cpu: "1024m"
    memory: "7Gi"
  limits:
    cpu: "3600m"
    memory: "10Gi"
  

config:
  create: true
  name: idrnd-documents-liveness-config
  data: {}

secret:
  create: false
  name: idrnd-documents-liveness-secrets

externalSecrets: []

scaledObject:
  enabled: true
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
    - type: memory
      metadata:
        type: Utilization
        value: "70"
