image:
  tag: iad-server-prod_2.4.1

service:
  labels:
    version: ""

config:
  data:
    SERVER_ALLOW_CORS: "true"
    SERVER_SSL_ENABLED: "true"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: qa-internal
    alb.ingress.kubernetes.io/load-balancer-name: qa-eks-internal-alb
    

externalSecrets:
  - name: liveness-injection-detection-external-secret
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: liveness-injection-detection-secrets
    data:
      - secretKey: SSL_KEY
        remoteRef:
          key: qa-internal-services-ssl-key
      - secretKey: SSL_CERT
        remoteRef:
          key: qa-internal-services-ssl-cert
      - secretKey: SSL_KEY_PASSWORD
        remoteRef:
          key: qa-internal-services-ssl-key-password
  
