image:
  tag: version_3.7.5_51c0e70_49

service:
  labels:
    version: "3.7.5"

config:
  data:
    SUPPORT_1_TO_MANY: "true"
    AWS_DEFAULT_REGION: "eu-central-1"
    ENABLE_ANALYTICS: "true"
    ENABLE_HTTPS: "true"
    SUPPORT_AGE_AND_GENDER: "true"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/5152bcf9-4464-4bb3-8953-014a10d654c5
    external-dns.alpha.kubernetes.io/ttl: "300"
    

externalSecrets:
  - name: ngfacematch-external-secret
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: ngfacematch-secrets
    data:
      - secretKey: KINESIS_STREAM_NAME
        remoteRef:
          key: dev_kinesis_credentials
          property: kinesis_stream
      - secretKey: SSL_KEY
        remoteRef:
          key: dev-eks-internal-services-ssl-key
      - secretKey: SSL_CERT
        remoteRef:
          key: dev-eks-internal-services-ssl-cert
      - secretKey: SSL_KEY_PASSWORD
        remoteRef:
          key: dev-eks-internal-services-ssl-key-password
  - name: ngfacematch-ssm-external-secret
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 5m
    targetName: ngfacematch-secrets
    data:
      - secretKey: FACE_DB_REDIS_URI
        remoteRef:
          key: dev-REDIS_URI-facematch
  
