image:
  tag: 

service:
  labels:
    version: ""

config:
  data:
    AUDIT: "true"
    DISABLE_LOG_TO_FILE: "true"
    SETUP_RABBITMQ: "true"
    AWS_DEFAULT_REGION: "eu-central-1"
    SESSIONS_SCHEDULER_INTERVAL_SECONDS: "20"
    DEFAULT_COMPANY: "63e353cbc81e405c6c692ffa"
    GOOGLE_APPLICATION_CREDENTIALS: "/app/auth/data.json"
    EXTRA_REDIS_TTL_SECONDS: "300"
    TIMED_OUT_SESSIONS_COMPLETION_DELAY_SECONDS: "10"
    AUTH_DB_SCHEMA: "eks_dev_authorization_375"
    IDRND_URI: "https://idrnd.dev-eks.internal-services:8443"
    SSL_CERT_CHAIN_SECRET_NAME: "dev-eks-internal-services-ssl-ca-crt"
    DB_SCHEMA: "dev_company"

ingress:
  annotations:
    {}
    

externalSecrets:
  - name: ngliveness-external-secret
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: 1h
    targetName: ngliveness-secrets
    data:
      - secretKey: IDENTITY_POOL_ID
        remoteRef:
          key: dev_kinesis_credentials
          property: identity_pool_id
      - secretKey: KINESIS_STREAM_NAME
        remoteRef:
          key: dev_kinesis_credentials
          property: kinesis_stream
      - secretKey: CLIENT_ID
        remoteRef:
          key: LIVENESS_AUTH_CLIENT
          property: LIVENESS_AUTH_CLIENT_ID
      - secretKey: CLIENT_SECRET
        remoteRef:
          key: LIVENESS_AUTH_CLIENT
          property: LIVENESS_AUTH_CLIENT_SECRET
  - name: ngliveness-ssm-external-secret
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 1h
    targetName: ngliveness-secrets
    data:
      - secretKey: DB_URI
        remoteRef:
          key: DB_URI-auth-eks-dev
      - secretKey: RABBIT_MQ_URI
        remoteRef:
          key: RABBIT_MQ_URI-dev
      - secretKey: REDIS_URI
        remoteRef:
          key: REDIS_URI-dev
  
