image:
  tag: version_3.7.5_d2d5060_138

service:
  labels:
    version: "3.7.5"

config:
  data:
    MODE: "saas"
    ENABLE_ANALYTICS: "true"
    AWS_DEFAULT_REGION: "eu-central-1"
    SSL_CERT_CHAIN_SECRET_NAME: "dev-eks-internal-services-ssl-ca-crt"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-external
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-external-alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/4a3a93b7-6a07-43f5-8d82-13ecd28be75e
    external-dns.alpha.kubernetes.io/ttl: "300"
    

externalSecrets:
  - name: ocr-external-secret
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: null
    targetName: ocr-secrets
    data:
      - secretKey: KINESIS_STREAM_NAME
        remoteRef:
          key: dev_kinesis_credentials
          property: kinesis_stream
      - secretKey: IDENTITY_POOL_ID
        remoteRef:
          key: dev_kinesis_credentials
          property: identity_pool_id
      - secretKey: AUTH_CLIENT_ID
        remoteRef:
          key: OCR_AUTH_V3_DEV
          property: AUTH_CLIENT_ID
      - secretKey: AUTH_CLIENT_SECRET
        remoteRef:
          key: OCR_AUTH_V3_DEV
          property: AUTH_CLIENT_SECRET
      - secretKey: JWT_SECRET_KEY
        remoteRef:
          key: OCR_JWT_SECRET_KEY
  - name: ocr-ssm-external-secret
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 1h
    targetName: ocr-secrets
    data:
      - secretKey: DB_URI
        remoteRef:
          key: DB_URI-auth-eks-dev
  
