image:
  tag: version_3.7.5_266717f_25

service:
  labels:
    version: "3.7.5"

config:
  data:
    CELLACT_COMPANY_NAME: "scan1"
    CELLACT_SENDER_NUMBER: "972797401829"
    CELLACT_CALLBACK_WAIT_TIME_SECONDS: "20"
    AWS_DEFAULT_REGION: "eu-central-1"
    EXPIRED_MESSAGES_SCHEDULER_DELAY_SECONDS: "30"
    STORAGE_SCHEMA: "dev_otp"
    TIME_TO_WAIT_BEFORE_CANCEL_MESSAGE_IN_SECONDS: "30"
    MESSAGE_TEMPLATE: "קוד האימות שלכם הוא {code} אני חוזר {code} תקף ל{expiration_time} דקות"
    CELLACT_DEFAULT_RATE: "-3"
    ENABLE_HTTPS: "true"
    CELLACT_API_URL: "https://la.cellactpro.com/xml"
    CELLACT_USER_NAME: "scan1"
    CELLACT_CALLBACK_URL: "https://otp_service.btrust/callback"
    CELLACT_PASSWORD: "wvc4x5ad"
    CELLACT_DEFAULT_VOICE: "M"

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
    external-dns.alpha.kubernetes.io/ttl: "300"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/5152bcf9-4464-4bb3-8953-014a10d654c5
    

externalSecrets:
  - name: otp-external-secrets
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    refreshInterval: 1h
    targetName: otp-secrets
    data:
      - secretKey: KINESIS_STREAM_NAME
        remoteRef:
          key: dev_kinesis_credentials
          property: kinesis_stream
      - secretKey: SSL_KEY
        remoteRef:
          key: dev-eks-internal-services-ssl-key
      - secretKey: SSL_CERT
        remoteRef:
          key: dev-eks-internal-services-ssl-cert
      - secretKey: SSL_KEY_PASSWORD
        remoteRef:
          key: dev-eks-internal-services-ssl-key-password
  - name: otp-ssm-external-secret
    secretStoreRef:
      name: aws-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 1h
    targetName: otp-secrets
    data:
      - secretKey: STORAGE_URL
        remoteRef:
          key: DB_URI-otp-dev
  
