apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liveness-injection-detection-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: qa-internal
    external-dns.alpha.kubernetes.io/hostname: liveness-injection-detection.qa-eks.internal-services
    alb.ingress.kubernetes.io/load-balancer-name: qa-eks-internal-alb
spec:
  ingressClassName: alb
  rules:
  - host: liveness-injection-detection.qa-eks.internal-services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: liveness-injection-detection-service
            port:
              number: 8443
