apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: idrnd-documents-liveness-base

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- scaledobject-keda.yaml

commonLabels:
  app: idrnd-documents-liveness
  managed-by: kustomize
