apiVersion: v1
kind: Service
metadata:
  name: idrnd-documents-liveness-service
  namespace: app
  labels:
    app: idrnd-documents-liveness
spec:
  type: ClusterIP
  ports:
  - name: 8443-tcp
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: idrnd-documents-liveness
