apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: liveness-injection-detection-ingress
  namespace: app
  labels:
    app: liveness-injection-detection
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/ttl: "300"
    alb.ingress.kubernetes.io/healthcheck-path: /api_version
    alb.ingress.kubernetes.io/healthcheck-port: '8443'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
spec:
  ingressClassName: alb
  rules:
  - host: liveness-injection-detection.internal-services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: liveness-injection-detection-service
            port:
              number: 8443
