apiVersion: v1
kind: Service
metadata:
  name: liveness-injection-detection-service
  namespace: app
  labels:
    app: liveness-injection-detection
spec:
  type: ClusterIP
  ports:
  - name: inj-8443-tcp
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: liveness-injection-detection
