apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    managed-by: helm
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- range $k, $v := .Values.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
