apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: console-dev

namespace: app

resources:
- ../../base
- external-secret-patch.yaml

patches:
- path: ingress-patch.yaml

configMapGenerator:
- name: console-config
  literals:
  - CAPTCHA_SOLVED_DELAY=250
  - PYTHONPATH=server
  - CLIENT_SECRET=K5#yea8Eeka8VCNfoQ2zkjgqvZ!pRm$k5Ul8y-AD
  - REQUEST_TIMEOUT=300
  - AWS_REGION=eu-central-1
  - ENABLE_DOCS=True
  - CAPTCHA_AFTER_FAILED_LOGINS=3
  - CAPTCHA_DOMAINS=purpleray.com,dev-local.com
  - SSL_CERT_CHAIN_SECRET_NAME=dev-eks-internal-services-ssl-ca-crt
  - CLIENT_ID=172Tvy5Yrb3h4XMY3daz7Xr1vzY1gh
  - CAPTCHA_ENABLED=1
  - FERNET_KEY=daYUf0bLc_e14x1aoprgcEpLp2RfSA-01FACKa6bZ2Q=

images:
- name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/console
  newTag: version_3.7.5_4c9b544_484

commonLabels:
  environment: dev
  version: "3.7.5"
