apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
spec:
  template:
    spec:
      containers:
      - name: ocr
        resources:
          requests:
            cpu: "1024m"
            memory: "2Gi"
          limits:
            cpu: "2048m"
            memory: "7Gi"
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: ssl-cert
          mountPath: /app/sslcert
          readOnly: true
      volumes:
      - name: app-logs
        hostPath:
          path: /logs
          type: DirectoryOrCreate
      - name: ssl-cert
        hostPath:
          path: /home/ec2-user/ocr/sslcert
          type: DirectoryOrCreate
