{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.configName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "service.labels" . | indent 4 }}
data:
{{- range $k, $v := .Values.config.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
