apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "service.fullname" . }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: {{ include "service.fullname" . }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
{{- $ports := .Values.service.ports }}
{{- if not (empty $ports) }}
{{- range $ports }}
        - name: {{ .name | default (printf "%d-tcp" (.port | int)) }}
          containerPort: {{ .targetPort | default .port }}
          protocol: {{ .protocol | default "TCP" }}
{{- end }}
{{- else }}
        - name: {{ printf "%d-tcp" (.Values.service.port | int) }}
          containerPort: {{ .Values.service.targetPort | default .Values.service.port }}
          protocol: TCP
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if or .Values.config.create .Values.sharedConfigRef.enabled .Values.secret.create (gt (len .Values.externalSecrets) 0) .Values.extraEnvFrom }}
        envFrom:
{{- if .Values.config.create }}
        - configMapRef:
            name: {{ include "service.configName" . }}
{{- end }}
{{- if and .Values.sharedConfigRef.enabled .Values.sharedConfigRef.name }}
        - configMapRef:
            name: {{ .Values.sharedConfigRef.name }}
{{- end }}
{{- if or .Values.secret.create (gt (len .Values.externalSecrets) 0) }}
        - secretRef:
            name: {{ include "service.secretName" . }}
{{- end }}
{{- if .Values.extraEnvFrom }}
{{ toYaml .Values.extraEnvFrom | indent 8 }}
{{- end }}
{{- end }}
{{- if or .Values.extraEnv (not (empty .Values.envVars)) }}
        env:
{{- range $k, $v := .Values.envVars }}
        - name: {{ $k }}
          value: {{ $v | quote }}
{{- end }}
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 8 }}
{{- end }}
{{- end }}
{{- if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 8 }}
{{- end }}
{{- if .Values.extraContainers }}
      {{- toYaml .Values.extraContainers | nindent 6 }}
{{- end }}
{{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
