{{- $total := len .Values.externalSecrets -}}
{{- range $i, $secret := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.namespace }}
  labels:
{{ include "service.labels" $ | indent 4 }}
spec:
  refreshInterval: {{ $secret.refreshInterval | default "5m" }}
  secretStoreRef:
    name: {{ $secret.secretStoreRef.name }}
    kind: {{ $secret.secretStoreRef.kind }}
  target:
    name: {{ $secret.targetName | default (include "service.secretName" $) }}
    creationPolicy: Merge
    template:
      mergePolicy: Merge
  data:
  {{- range $secret.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      {{- if .remoteRef.property }}
      property: {{ .remoteRef.property }}
      {{- end }}
  {{- end }}
{{- if lt (add1 $i) $total }}
---
{{- end }}
{{- end }}
