{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "service.fullname" .) }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "service.labels" . | indent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "service.ingressHost" . }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ include "service.ingressHost" . }}
    http:
      paths:
{{- range .Values.ingress.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ default (printf "%s-service" (include "service.fullname" $)) .serviceName }}
            port:
              number: {{ .port | default $.Values.service.port }}
{{- end }}
{{- end }}
