{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "service.labels" . | indent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
