apiVersion: apps/v1
kind: Deployment
metadata:
  name: idrnd
  namespace: app
  labels:
    app: idrnd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idrnd
  template:
    metadata:
      labels:
        app: idrnd
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: idrnd
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/idrnd:latest
        ports:
        - name: 8443-tcp
          containerPort: 8443
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "5Gi"
          limits:
            cpu: "3600m"
            memory: "7Gi"
        envFrom:
        - configMapRef:
            name: idrnd-config
