apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: app
  labels:
    app: console
spec:
  replicas: 2
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: console
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/console:latest
        ports:
        - name: 8010-tcp
          containerPort: 8010
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "1Gi"
          limits:
            cpu: "2048m"
            memory: "2Gi"
        envFrom:
        - configMapRef:
            name: console-config
        - secretRef:
            name: console-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
