apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: app
  labels:
    app: console
spec:
  type: ClusterIP
  ports:
  - name: 8010-tcp
    port: 8010
    protocol: TCP
    targetPort: 8010
  selector:
    app: console
