apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngliveness
  namespace: app
  labels:
    app: ngliveness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngliveness
  template:
    metadata:
      labels:
        app: ngliveness
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: ngliveness
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/ng_liveness:latest
        ports:
        - name: 5009-tcp
          containerPort: 5009
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "6Gi"
          limits:
            cpu: "2048m"
            memory: "7Gi"
        envFrom:
        - configMapRef:
            name: ngliveness-config
        - secretRef:
            name: ngliveness-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
