apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngliveness-ingress
  namespace: app
  labels:
    app: ngliveness
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: alb
  rules:
  - host: ngliveness-eks.purpleray.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ngliveness-service
            port:
              number: 5009
