apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngfacematch-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: dev-internal
    alb.ingress.kubernetes.io/load-balancer-name: dev-eks-internal-alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:495947449196:certificate/5152bcf9-4464-4bb3-8953-014a10d654c5
    external-dns.alpha.kubernetes.io/hostname: ngfacematch.dev-eks.internal-services
    external-dns.alpha.kubernetes.io/ttl: "300"

spec:
  rules:
  - host: ngfacematch.dev-eks.internal-services
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ngfacematch-service
            port:
              number: 3000
