apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: app
  labels:
    app: portal
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: 8000-tcp
  - port: 8020
    targetPort: 8020
    protocol: TCP
    name: 8020-tcp
  selector:
    app: portal
