apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services-helm
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: qa
                  # cluster: https://EDD3DC524CE31643A25033C9775AA6DF.gr7.eu-central-1.eks.amazonaws.com
          - list:
              elements:
                # - svc: authorization
                # - svc: client-onboarding
                # - svc: console
                - svc: dummy-app
                # - svc: facesplit
                # - svc: idrnd
                # - svc: idrnd-documents-liveness
                # - svc: liveness
                # - svc: liveness-injection-detection
                # - svc: liveness-presentation-detection
                # - svc: ngfacematch
                # - svc: ngliveness
                # - svc: ngocr
                # - svc: ocr
                # - svc: otp
                # - svc: portal
                - svc: shared-infra
                # - svc: video-statement
  template:
    metadata:
      name: "{{.svc}}-{{.env}}"
      labels:
        app: "{{.svc}}"
        environment: "{{.env}}"
        managed-by: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ if eq .svc "shared-infra" }}-1{{ else }}0{{ end }}'
    spec:
      project: "scanovate-{{.env}}"
      source:
        repoURL: https://bitbucket.org/scanovate/eks-argocd-deployment.git
        targetRevision: main
        path: '{{ if eq .svc "shared-infra" }}helm/charts/shared-infra{{ else }}helm/charts/service{{ end }}'
        helm:
          valueFiles:
            - "../../values/global.yaml"
            - "../../values/envs/{{.env}}.yaml"
            - "../../values/envs/{{.env}}.shared-config.yaml"
            - "../../values/services/{{.svc}}.yaml"
            - "../../values/services/{{.svc}}-{{.env}}.yaml"
          ignoreMissingValueFiles: true
      destination:
        server: '{{ default "https://kubernetes.default.svc" .cluster }}'
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
