apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: scanovate-projects
  annotations:
    description: "ArgoCD Projects for Scanovate environments"

resources:
- scanovate-dev.yaml
- scanovate-qa.yaml
- scanovate-staging.yaml
- scanovate-production.yaml
- scanovate-repository.yaml

commonLabels:
  app.kubernetes.io/name: scanovate-projects
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
