apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shared-infrastructure
  annotations:
    description: "Shared infrastructure for staging environment"

resources:
- ../../base
- serviceaccount.yaml

commonLabels:
  environment: staging

commonAnnotations:
  environment: staging
