apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: liveness-injection-detection-dev

namespace: app

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base
- external-secret-patch.yaml

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: liveness-injection-detection-ingress

configMapGenerator:
- name: liveness-injection-detection-config
  literals:
  - SERVER_ALLOW_CORS=true
  - SERVER_SSL_ENABLED=true

images:
- name: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/liveness_injection_detection
  newTag: iad-server-prod_2.4.1

commonLabels:
  environment: dev

commonAnnotations:
  environment: "development"
