apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
  namespace: app
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      serviceAccountName: app-services-sa
      containers:
      - name: ocr
        image: 495947449196.dkr.ecr.eu-central-1.amazonaws.com/ocr:latest
        ports:
        - name: 5040-tcp
          containerPort: 5040
          protocol: TCP
        resources:
          requests:
            cpu: "1024m"
            memory: "6Gi"
          limits:
            cpu: "2048m"
            memory: "7Gi"
        envFrom:
        - configMapRef:
            name: ocr-config
        - secretRef:
            name: ocr-secrets
        env:
        - name: AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: shared-configmap
              key: AUTH_URL
