apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocr-nginx-ingress
  namespace: app
  labels:
    app: ocr
  annotations:
    nginx.ingress.kubernetes.io/upstream-hash-by: "$http_session_id"
    nginx.ingress.kubernetes.io/upstream-hash-by-subset: "true"
    nginx.ingress.kubernetes.io/upstream-hash-by-subset-size: "3"
spec:
  ingressClassName: nginx
  rules:
  - host: ocr-eks.purpleray.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ocr-service
            port:
              number: 5040
