apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ocr-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-nginx.yaml
  - secret.yaml
  - scaledobject-keda.yaml

commonLabels:
  app: ocr
  component: ocr-service

commonAnnotations:
  description: "OCR Service for document processing"
